const BOOKLISTS = [
  {
    title: "Celebrate Your Independent Bookstore (digital edition)",
    "item-titles": [
      "The Book Itch",
      "The Storied Life of A. J. Fikry",
      "How to Find Love in A Bookshop",
      "The Bookshop of Yesterdays",
      "The Printed Letter Bookshop",
      "The Little Paris Bookshop",
      "The Bookshop of the Broken Hearted",
      "The Bookshop on the Corner",
      "Mr. Penumbra's 24-Hour Bookstore",
      "The Lost for Words Bookshop",
      "Midnight at the Bright Ideas Bookstore",
      "The Secret, Book & Scone Society",
      "The Cracked Spine",
      "Crime and Poetry The Plot Is Murder",
      "Footnotes From the World's Greatest Bookstores",
    ],
    "item-authors": [
      "Vaunda Micheaux Nelson",
      "Gabrielle Zevin",
      "Veronica Henry",
      "Amy Meyerson",
      "Katherine Reay",
      "Nina George",
      "Robert Hillman",
      "Jenny Colgan",
      "Robin Sloan",
      "Stephanie Butland",
      "Matthew Sullivan",
      "Ellery Adams",
      "Paige Shelton",
      "Amanda Flower",
      "V.M. Burns",
      "Bob Eckstein",
    ],
    keywords: [
      "adventure",
      "cozy",
      "humor",
      "love",
      "loss",
      "romance",
      "mystery",
      "magic",
      "black",
    ],
    genre: ["Historical Fiction", "Literary Fiction", "Mystery", "Thriller"],
    "fic-nonfic": ["Fiction", "Non-fiction"],
    appeal: [
      "character-driven",
      "culturally diverse",
      "funny",
      "lyrical",
      "romantic",
      "strong female protagonist",
      "suspenseful",
    ],
    language: "English",
    "audience-age": ["Adults", "Children"],
  },
  {
    title: "What Hillsboro Public Library Staff are Streaming Part 2",
    "item-titles": [
      "LUNCH DOODLES",
      "Caspar Babypants",
      "Narwhal and Jelly Live Sessions",
      "Yoga For Beginners 20 Minute Kids Yoga Class",
      "Procreate tutorial ipad",
      "The Valhalla Murders",
      "Stream live concerts npr",
      "Son of Rambow",
      "Growing Up Smith",
      "Altered Carbon",
      "Ozark",
      "Poldark",
      "The 100",
      "Detectorists",
      "Carnival Row",
    ],
    "item-authors": [
      "Mo Willems",
      "Ben Clanton",
      "Frank Lotito",
      "Garth Jennings",
    ],
    keywords: [
      "music",
      "detective",
      "fairy",
      "murder",
      "wistful",
      "love",
      "future",
      "Indian",
    ],
    genre: ["Historical Fiction", "Mystery", "SciFi"],
    "fic-nonfic": ["Fiction", "Non-fiction"],
    appeal: [
      "action-packed",
      "character-driven",
      "culturally diverse",
      "funny",
      "romantic",
      "suspenseful",
      "thought-provoking",
    ],
    language: "English",
    "audience-age": ["Adults", "Children"],
  },
  {
    title: "Podcasts for History Buffs",
    "item-titles": [
      "The Memory Palace",
      "Cabinet of Curiosities",
      "Outliers",
      "Footnoting History",
      "The Past and The Curious",
      "Useless Information",
      "Stuff You Missed in History Class",
      "The History of Egypt Podcast",
      "Sawbones: A Marital Tour of Misguided Medicine",
      "You Must Remember This",
      "Tides of History",
      "The History of China",
      "The History of England",
      "The British History Podcast",
    ],
    "item-authors": [
      "David Crowther",
      "Patrick Wyman",
      "Karina Longworth",
      "Sydnee McElroy",
      "Holly Frey",
      "Tracy Wilson",
      "Mick Sullivan",
    ],
    keywords: "audio",
    genre: "History",
    "fic-nonfic": "Non-fiction",
    appeal: ["atmospheric", "culturally diverse", "thought-provoking"],
    language: "English",
    "audience-age": ["Adults", "Children"],
  },
  {
    title: "HPL at Home: What Library Staff Are Reading",
    "item-titles": [
      "Oona Out of Order",
      "Sorcery of Thorns",
      "The Sisters of the Winter Wood",
      "Monstress Volume 1",
      "Tuesday Mooney Talks to Ghosts",
      "We Used to Be Friends",
      "Spinning Silver",
      "Rosemary and Rue",
      "The Ten Thousand Doors of January",
    ],
    "item-authors": [
      "Margarita Montimore",
      "Margaret Rogerson",
      "Rena Rossner",
      "Marjorie Liu",
      "Kate Racculia",
      "Amy Spalding",
      "Naomi Novik",
      "Seanan McGuire",
      "Alix E. Harrow",
    ],
    keywords: [
      "time travel",
      "sarcastic",
      "ghosts",
      "family",
      "historical",
      "mystery",
      "magic",
      "adventure",
      "love",
      "fairies",
    ],
    genre: ["Fantasy", "Graphic Novel", "Literary Fiction", "Mystery"],
    "fic-nonfic": "Fiction",
    appeal: [
      "bittersweet",
      "character-driven",
      "intricately plotted",
      "romantic",
      "strong female protagonist",
      "world-building",
    ],
    language: "English",
    "audience-age": ["Adults", "Teens"],
  },
  {
    title:
      "Digging Up Intrigue: Archaeological mysteries, suspense, and thrillers (digital edition)",
    "item-titles": [
      "The Crossing Places",
      "Crocodile on the Sandbank",
      "The Shadowy Horses",
      "Labyrinth",
      "A Treacherous Curse",
      "Women of the Dunes",
      "Birthright",
      "The Visitors",
      "The Keepsake",
      "The Crowded Grave",
      "The Cursed Key",
      "Excavation",
      "The Hunt for Atlantis",
      "The Bone Labyrinth",
      "Timeline",
      "The Engines of God",
    ],
    "item-authors": [
      "Elly Griffiths",
      "Elizabeth Peters",
      "Susanna Kearsley",
      "Kate Mosse",
      "DEANNA RAYBOURN",
      "Sarah Maine",
      "Nora Roberts",
      "Sally Beauman",
      "Tess Gerritsen",
      "Martin Walker",
      "Rebecca Hamilton",
      "James Rollins",
      "Andy McDermott",
      "Michael Crichton",
      "Jack McDevitt",
    ],
    keywords: [
      "history",
      "techno-thriller",
      "escape",
      "intrigue",
      "adventure",
      "danger",
      "romance",
      "future",
      "paranormal",
      "egypt",
    ],
    genre: ["Mystery", "Thriller"],
    "fic-nonfic": "Fiction",
    appeal: [
      "atmospheric",
      "character-driven",
      "compelling",
      "fast-paced",
      "haunting",
      "strong female protagonist",
      "suspenseful",
      "well-developed characters",
    ],
    language: "English",
    "audience-age": "Adults",
  },
  {
    title: "Because You're Living in a Virtual World",
    "item-titles": [
      "Snow Crash",
      "Neuromancer",
      "City of Golden Shadow",
      "Lock In",
      "The Chalk Artist",
      "Tomorrow and Tomorrow",
      "Total Recall",
      "Ready Player One",
      "Warcross",
      "Fallout",
      "The Leveller",
      "In Real Life",
      "Otherworld",
      "The Eye of Minds",
      "Insignia",
    ],
    "item-authors": [
      "Neal Stephenson",
      "William Gibson",
      "Tad Williams",
      "John Scalzi",
      "Allegra Goodman",
      "Tom Sweterlitsch",
      "Philip K. Dick",
      "Ernest Cline",
      "Marie Lu",
      "Gwenda Bond",
      "Julia Durango",
      "cory doctorow",
      "Kirsten Miller",
      "James Dashner",
      "S. J. Kincaid",
    ],
    keywords: [
      "cyberpunk",
      "conspiracy",
      "online",
      "virtual reality",
      "video game",
      "danger",
      "hacker",
      "spy",
      "intense",
      "robots",
    ],
    genre: [
      "Graphic Novel",
      "Literary Fiction",
      "Mystery",
      "SciFi",
      "Thriller",
    ],
    "fic-nonfic": "Fiction",
    appeal: [
      "action-packed",
      "character-driven",
      "compelling",
      "fast-paced",
      "intricately plotted",
      "strong female protagonist",
      "world building",
    ],
    language: "English",
    "audience-age": ["Teens", "Adults"],
  },
  {
    title: "Memorias de mujeres en Español",
    "item-titles": [
      "En el país que amamos",
      "Perdón",
      "Viviendo",
      "Una Vida",
      "Cuando era puertorriqueña",
      "Becoming",
      "Una reina como tú",
      "En el cuerpo correcto",
      "Tomboy",
      "Mi mundo adorado",
      "La búsqueda de un sueño",
    ],
    "item-authors": [
      "Diane Guerrero",
      "Chiquis Rivera",
      "Adamari Lopez",
      "Ednita Nazario",
      "Esmeralda Santiago",
      "Michelle Obama",
      "Francisca Lachapel",
      "Morganna Love",
      "Liz Prince",
      "Sonia Sotomayor",
      "Reyna Grande",
    ],
    keywords: [
      "inspiring",
      "immigration",
      "immigrant",
      "humor",
      "family",
      "cancer",
    ],
    genre: "Memoir",
    "fic-nonfic": "Non-fiction",
    appeal: ["culturally diverse", "strong female protagonist"],
    language: "Español",
    "audience-age": "Adults",
  },
  {
    title: "Women's Memoirs",
    "item-titles": [
      "I Am, I Am, I Am",
      "Just Kids",
      "In the Country We Love",
      "Men We Reaped",
      "The Argonauts",
      "Sex Object",
      "Ordinary Girls",
      "We Are Not Here to Be Bystanders",
      "Hunger",
      "From Scratch",
      "Know My Name",
      "Reading Lolita in Tehran",
      "Furiously Happy",
      "The Princess Diarist",
      "Yes Please",
      "Becoming",
      "Tomboy",
      "The Best We Could Do",
      "Untamed",
      "The Woman Warrior",
    ],
    "item-authors": [
      "Maggie O'Farrell",
      "Patti Smith",
      "Diane Guerrero",
      "Jesmyn Ward",
      "Maggie Nelson",
      "Jessica Valenti",
      "Jaquira Diaz",
      "Linda Sarsour",
      "Roxane Gay",
      "Tembi Locke",
      "Chanel Miller",
      "Azar Nafisi",
      "Jenny Lawson",
      "Carrie Fisher",
      "Amy Poehler",
      "Michelle Obama",
      "Liz Prince",
      "Thi Bui",
      "Glennon Doyle",
      "Maxine Hong Kingston",
    ],
    keywords: [
      "asian",
      "autobiography",
      "muslim",
      "black",
      "latina",
      "undocumented",
      "immigration",
      "immigrant",
      "racism",
      "poverty",
      "sexuality",
    ],
    genre: "Memoir",
    "fic-nonfic": "Non-fiction",
    appeal: ["culturally diverse", "lgbtqia+", "strong female protagonist"],
    language: "English",
    "audience-age": "Adults",
  },
  {
    title: "Hillsboro Staff Picks: Podcasts",
    "item-titles": [
      "Punch Up the Jam",
      "Starship Iris",
      "Heavyweight",
      "You're Wrong About",
      "Passenger List",
      "Dolly Parton's America",
      "The Message",
      "Reply All",
      "The Dream",
      "The Adventure Zone",
      "Articles of Interest",
      "City of the Future",
      "Criminal",
      "99% Invisible",
      "You Must Remember This",
      "Wonderful",
      "On the Media",
      "Flash Forward",
      "Personal Best",
    ],
    "item-authors": [
      "Miel Bredouw",
      "Demi Adejuyigbe",
      "Johnathan Goldstein",
      "Michael Hobbes",
      "Sarah Marshall",
      "PJ Vogt",
      "Jane Marie",
      "Dann Gallucci",
      "McElroy",
      "Avery Trufelman",
      "Phoebe Judge",
      "Karina Longworth",
    ],
    keywords: [
      "audio",
      "psychology",
      "science",
      "journalism",
      "Hollywood",
      "architecture",
      "design",
      "true crime",
      "future",
      "music",
    ],
    genre: ["Fantasy", "History", "SciFi", "Thriller"],
    "fic-nonfic": ["Fiction", "Non-fiction"],
    appeal: ["compelling", "culturally diverse", "funny", "thought-provoking"],
    language: "English",
    "audience-age": "Adults",
  },
  {
    title: 'Staff Recommended "Always Available" Audiobooks',
    "item-titles": [
      "Citizen",
      "The Ghost Map",
      "So You Want to Talk About Race",
      "Stiff",
      "Gulp",
      "The Screwtape Letters",
      "A Tale for the Time Being",
      "Penric's Demon",
      "River of Teeth",
      "Lady Osbaldestone's Christmas Goose",
      "Brave New World",
      "Hunter",
      "Gone",
      "Splintered",
      "The Birchbark House",
      "Insignificant Events in the Life of A Cactus",
    ],
    "item-authors": [
      "Claudia Rankine",
      "Steven Johnson",
      "Ijeoma Oluo",
      "Mary Roach",
      "C. S. Lewis",
      "Ruth Ozeki",
      "Lois Mcmaster Bujold",
      "Sarah Gailey",
      "Stephanie Laurens",
      "Aldous Huxley",
      "Mercedes Lackey",
      "Grant, Michael",
      "A. G. Howard",
      "Louise Erdrich",
      "Dusti Bowling",
    ],
    keywords: [
      "dystopian",
      "poetry",
      "satire",
      "family",
      "history",
      "Native Americans",
      "friendship",
    ],
    genre: ["Fantasy, Literary Fiction, Mystery, Romance, SciFi"],
    "fic-nonfic": ["Fiction", "Non-fiction"],
    appeal: [
      "ability diverse",
      "bittersweet",
      "culturally diverse",
      "funny",
      "lgbtqia+",
      "romantic",
      "thought-provoking",
      "well-developed characters",
    ],
    language: "English",
    "audience-age": ["Adults", "Children", "Teens"],
  },
  {
    title: "Political Topics to Bring Us Together",
    "item-titles": [
      "The Soul of America",
      "I Think You're Wrong (but I'm Listening) A Guide to Grace-filled Political Conversations",
      "Love your Enemies How Decent People Can Save America From the Culture of Contempt",
      "The Conservative Sensibility",
      "Doubt A History : the Great Doubters and Their Legacy of Innovation",
      "Them Why We Hate Each Other and How to Heal",
      "Republican Like Me How I Left the Liberal Bubble and Learned to Love the Right",
      "The Righteous Mind Why Good People Are Divided by Politics and Religion",
      "Tribe On Homecoming and Belonging",
      "Talking Across the Divide How to Communicate With People You Disagree With and Maybe Even Change the World",
      "Why We're Polarized",
      "Collaborating With the Enemy How to Work With People You Don't Agree With or Like or Trust",
    ],
    "item-authors": [
      "Jon Meacham",
      "Sarah Stewart Holland",
      "Arthur C. Brooks",
      "George F. Will",
      "Jennifer Michael Hecht",
      "Benjamin E. Sasse",
      "Ken Stern",
      "Jonathan Haidt",
      "Sebastian Junger",
      "Justin Lee",
      "Ezra Klein",
      "Adam Kahane",
    ],
    keywords: ["polisci", "empathy", "nationalism"],
    genre: "Social Science",
    "fic-nonfic": "Non-fiction",
    appeal: "thought-provoking",
    language: "English",
    "audience-age": "Adults",
  },
  {
    title: "Find Your Next: Short Stories",
    "item-titles": [
      "How Long 'til Black Future Month?",
      "This Is How You Lose Her",
      "Her Body and Other Parties",
      "Ayiti",
      "American Innovations",
      "A Good Man Is Hard to Find, and Other Stories",
      "The Thing Around your Neck",
      "A People's Future of the United States Speculative Fiction From 25 Extraordinary Writers",
      "Growing Things",
      "What Is Not Yours Is Not Yours",
      "No One Belongs Here More Than You",
    ],
    "item-authors": [
      "N. K. Jemisin",
      "Junot Díaz",
      "Carmen Maria Machado",
      "Roxane Gay",
      "Rivka Galchen",
      "Flannery O'Connor",
      "Chimamanda Ngozi Adichie",
      "Paul Tremblay",
      "Helen Oyeyemi",
      "Miranda July",
    ],
    keywords: [
      "unconventional",
      "ghosts",
      "love",
      "complex",
      "dragons",
      "dystopian",
      "hope",
      "family",
      "southern gothic",
      "Haiti",
      "law",
      "order",
    ],
    genre: ["Literary Fiction, Horror, SciFi"],
    "fic-nonfic": "Fiction",
    appeal: [
      "atmospheric",
      "bittersweet",
      "character-driven",
      "culturally diverse",
      "haunting",
      "leisurely paced",
      "strong female protagonist",
      "suspenseful",
    ],
    language: "English",
    "audience-age": "Adults",
  },
  {
    title: "Books That Changed Us: The Artists of Bag&Baggage",
    "item-titles": [
      "The Bad Beginning",
      "The Family Under the Bridge",
      "The Autobiography of Malcolm X",
      "Basic Writings of Nietzsche",
      "Madame Bovary",
    ],
    "item-authors": [
      "Lemony Snicket",
      "Natalie Savage Carlson",
      "Friedrich Wilhelm Nietzsche",
      "Gustave Flaubert",
    ],
    keywords: ["feminist", "race", "family", "home", "civil rights"],
    genre: ["Literary Fiction", "Memoir", "Philosophy"],
    "fic-nonfic": ["Fiction", "Non-fiction"],
    appeal: ["culturally diverse", "funny", "thought-provoking"],
    language: "English",
    "audience-age": ["Adults", "Children"],
  },
];
